/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Dog = IDL.Record({
  'id' : IDL.Text,
  'accessory' : IDL.Text,
  'name' : IDL.Text,
  'coatColor' : IDL.Text,
  'mintedAt' : IDL.Int,
  'eyeColor' : IDL.Text,
  'breed' : IDL.Text,
});
export const MintDogInput = IDL.Record({
  'accessory' : IDL.Text,
  'name' : IDL.Text,
  'coatColor' : IDL.Text,
  'eyeColor' : IDL.Text,
  'breed' : IDL.Text,
});

export const idlService = IDL.Service({
  'getDogById' : IDL.Func([IDL.Text], [IDL.Opt(Dog)], ['query']),
  'getMyDogs' : IDL.Func([], [IDL.Vec(Dog)], ['query']),
  'mintDog' : IDL.Func([MintDogInput], [Dog], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Dog = IDL.Record({
    'id' : IDL.Text,
    'accessory' : IDL.Text,
    'name' : IDL.Text,
    'coatColor' : IDL.Text,
    'mintedAt' : IDL.Int,
    'eyeColor' : IDL.Text,
    'breed' : IDL.Text,
  });
  const MintDogInput = IDL.Record({
    'accessory' : IDL.Text,
    'name' : IDL.Text,
    'coatColor' : IDL.Text,
    'eyeColor' : IDL.Text,
    'breed' : IDL.Text,
  });
  
  return IDL.Service({
    'getDogById' : IDL.Func([IDL.Text], [IDL.Opt(Dog)], ['query']),
    'getMyDogs' : IDL.Func([], [IDL.Vec(Dog)], ['query']),
    'mintDog' : IDL.Func([MintDogInput], [Dog], []),
  });
};

export const init = ({ IDL }) => { return []; };